### ISSUE TITLE
Deadlock on Python 3.6 on macOS

### ISSUE THREAD

**Issue by mdekstrand** [lenskit/lkpy#166]
The tests do not successfully finish on Python 3.6 on macOS - suspect a deadlock.

This seems to be a deadlock in `multiprocessing.Pool`, which is known to deadlock in some cases.

**Comment by Helma-T** [comment]
The same applies to Ubuntu user, with Python 3.6
The deadlock in my case seems to be the result of processes not being terminated after the job is done. I end up with too many zombie processes afterward, which seems to be the problem.

**Comment by mdekstrand** [comment]
@Helma-T I've also opened a [discussion on the Google Group](https://groups.google.com/g/lenskit-recsys/c/4YBd5ajCsvA) about the future of Python 3.6 support. Please feel free to contribute there as we figure out how much effort to put on this bug.

**Comment by mdekstrand** [comment]
Since the Google Group discussion did not yield opposition to adopting [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html), the NumPy standard for Python version support, we will be dropping support for Python 3.6 in LensKit 0.13. Given that 3.7 has a fix for this issue, and fixing it would require importing significant new libraries only to no longer need them, I'm going to close this issue.

If issues persist in a Python 3.7 environment, we can reopen or create a new issue.

Thanks for bumping it @Helma-T, and please let me know if I can help get one of the workarounds working for you!
