### ISSUE TITLE
Bus error running example code

### ISSUE THREAD

**Issue by mdekstrand** [lenskit/lkpy#197]
@frankkloster reports in #195:

> Thank you so much for getting back to me with this! Installed everything in a clean environment,
>
> ```
> conda create -n lenskit_env
> conda activate lenskit_env
> conda install pip
> pip install lenskit
> ```
>
> Running the same code now returns Bus error (core dumped), as well as a notice that a thread hasn't successfully closed. This might be a separate issue, though.

Moving here to track separately.

**Comment by mdekstrand** [comment]
I have so far been unable to reproduce this error.

@frankkloster Does it work if you do `conda install -c lenskit lenskit`?

**Comment by frankkloster** [comment]
@mdekstrand I apologize here. Turns out, starting a clean docker environment seemed to fix the issue. Not entirely what the issue was previously. I'll open this up again if I'm able to reproduce this error.

**Comment by mdekstrand** [comment]
@frankkloster Thanks for following up! I'll close for now.
