### ISSUE TITLE
Support scipy.sparse.coo_matrix in sparse_ratings

### ISSUE THREAD

**Issue by reppertj** [lenskit/lkpy#213]
It would be good for `sparse_ratings` to support creating a `scipy.sparse.coo_matrix` directly, so integrations can use it. As it is, it returns `scipy.sparse.csr_matrix` with `scipy=True`. This can be enabled with an additional keyword argument without breaking existing usage of the API.

(This is needed for the lightfm integration in issue #188; as it is, we either have to perform an additional conversion after calling `sparse_ratings` or substantially reproduce its functionality).

**Comment by reppertj** [comment]
I can make this change if you want to go this route; just wanted to raise a separate issue for it.

**Comment by mdekstrand** [comment]
Yes, this seems like a good idea. Either a new keyword argument; modifying the existing argument to optionally take a string could also work:

- `scipy=True` or `scipy='csr'`: make CSR matrix
- `scipy='coo'`: make COO matrix

Splitting into a separate issue is a good idea. If it isn't too much work to also make a separate PR, that will make the resulting release notes easier (I use release-drafter to automatically include a list of merged PRs in the release notes).
