### ISSUE TITLE
openmp enabled linux wheels with cibuildwheel

### ISSUE THREAD

**Issue by benfred** [lenskit/lkpy#23]
(continuing conversation from twitter - since I couldn't all this in a tweet).

I think the [example travis config file will almost work for you from cibuildwheel](https://github.com/joerick/cibuildwheel/#minimal-setup) - unfortunately I don't know enough about circleci to help out with setting that up =(.

I tested cibuildwheel for lkpy by building wheels using docker w/ cibuildwheel (I built on OSX, but everything here should work on linux).

After installing docker, and making sure docker is running - the commands to generate the wheels were:
```
pip install cibuildwheel
git clone git@github.com:lenskit/lkpy.git
cd lkpy

# python 3.7 needs hdf5 headers, this will install them in the docker container
# likewise python 3.5 needed numpy installed first for some reason
export CIBW_BEFORE_BUILD="yum install -y hdf5-devel; pip install numpy"

# I only tested building wheels for python 3.5/3.6
# It doesn't seem like setup.py is valid syntax for python2.7/3.3/3.4 since you are
# relying on this feature  https://www.python.org/dev/peps/pep-0448/ on line 72 which
# was added in python 3.5.
# Python 3.7 didn't work ... but probably can be made to work without too much effort
# setting this environment variable will cause cibuildwheel to skip those versions
export CIBW_SKIP='cp27* cpy33* cp34* cp37*'

cibuildwheel --output-dir wheelhouse --platform linux
```

This dumps out a series of wheel files into a 'wheelhouse' subdirectory:
```
lkpy ben$ ls wheelhouse/
lenskit-0.1.0-cp35-cp35m-manylinux1_i686.whl
lenskit-0.1.0-cp35-cp35m-manylinux1_x86_64.whl
lenskit-0.1.0-cp36-cp36m-manylinux1_i686.whl
lenskit-0.1.0-cp36-cp36m-manylinux1_x86_64.whl
```

I took one of them and installed on a ubuntu system and it worked with multi-threaded training and auditwheel didn't flag anything crazy to me or return an error:
```

>$ auditwheel show lenskit-0.1.0-cp36-cp36m-manylinux1_x86_64.whl

lenskit-0.1.0-cp36-cp36m-manylinux1_x86_64.whl is consistent with the
following platform tag: "manylinux1_x86_64".

The wheel references external versioned symbols in these system-
provided shared libraries: librt.so.1 with versions {'GLIBC_2.2.5'},
libpthread.so.0 with versions {'GLIBC_2.2.5', 'GLIBC_2.3.4'},
libc.so.6 with versions {'GLIBC_2.3', 'GLIBC_2.2.5', 'GLIBC_2.4'},
libgomp-3300acd3.so.1.0.0 with versions {'GOMP_1.0', 'OMP_1.0'}

The following external shared libraries are required by the wheel:
{
    "libc.so.6": "/lib/x86_64-linux-gnu/libc-2.23.so",
    "libpthread.so.0": "/lib/x86_64-linux-gnu/libpthread-2.23.so",
    "librt.so.1": "/lib/x86_64-linux-gnu/librt-2.23.so"
}
```

It does seem like cibuildwheel is doing something to install libgomp with your package, the linked libgomp package is installed with the lenskit package (to site-packages/lenskit/.lib/libgomp...)

```
>$ ldd ~/anaconda3/lib/python3.6/site-packages/lenskit/algorithms/_item_knn.cpython-36m-x86_64-linux-gnu.so
        linux-vdso.so.1 =>  (0x00007ffcb168d000)
        libgomp-3300acd3.so.1.0.0 => /home/ben/anaconda3/lib/python3.6/site-packages/lenskit/algorithms/../.libs/libgomp-3300acd3.so.1.0.0 (0x00007f349359d000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3493380000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3492fb6000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f3492dae000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f34939e6000)
```

The error I saw from python 3.7 was complaining about the installed hdf5 version being too old (dependency of tables that was getting installed). It shouldn't be too hard to hack around

I've been mainly using cibuildwheel for rust extensions so far - I wrote up how to do this here: https://www.benfrederickson.com/writing-python-extensions-in-rust-using-pyo3/ , the relevant bits to you are at the end (and talk about setting up appveyor/travis to automatically upload wheels to pypi for you whenever the version is bumped).

Anyways hope this helps =) I find all this python packaging stuff to be a bit of a pain myself ...

**Comment by mdekstrand** [comment]
Very interesting, thank you!

We don't support Python < 3.5 (I don't see a need to support Pythons older than those shipped with the latest LTS releases of major Linux distros).

I am not sure how I feel about bundling libgomp (and will need to do a double-check on the licensing of that). Will want to look at numpy & scipy and see what they include in their wheels in terms of OpenMP and BLAS implementations.

**Comment by mdekstrand** [comment]
I have done some more digging to better understand how numpy & scipy package.

Their wheels each contain a copy of the GNU Fortran runtime library (`libgfortran`) and OpenBLAS (`libopenblasp`). The OpenBLAS they ship seems to be parallel but without OpenMP (it links against `libpthread`).

We use BLAS through SciPy, so hopefully we are using SciPy's BLAS library and not re-packaging it ourselves.

My understanding of the GCC Runtime Exception to the GPL is that we are fine including `libgomp` if we want. However, if we're imported in another process that also uses OpenMP, but links in a different OpenMP runtime, there may be problems?

It seems we have three possible solutions:

1. Deploy this solution and publish binary wheels including the `libgomp` solib, possibly duplicating shared libraries.
2. Publish binary wheels with OpenMP disabled.
3. Only publish an `sdist`, and let non-Conda users compile their own (at least on Linux, where most scientific users will have a compiler already installed).

**Comment by mdekstrand** [comment]
Yay numba!
