### ISSUE TITLE
Unable to import lenskit modules using fast-parquet

### ISSUE THREAD

**Issue by JacobMaciejewski** [lenskit/lkpy#253]
The following issue appeared today (having used lenskit two days ago, everything was fine). I am unable to import any lenskit module that expects init fastparquet.speedups(). When trying to import MultiEval, batch e.t.c. I am getting the following error:

![parquet](https://user-images.githubusercontent.com/71031279/117574758-5088ab00-b0e7-11eb-8d5f-cdee4205e24a.JPG)

`/usr/local/lib/python3.7/dist-packages/fastparquet/speedups.pyx in init fastparquet.speedups()

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject`

I am currently running numpy 1.19.5 and the whole development is taking place on Google Colab.

Any clues on how to solve this problem?

**Comment by mdekstrand** [comment]
It looks like Fastparquet released a new version earlier this week. I plan to drop the fastparquet attempted dependency in a future LensKit; in the mean time, can you constrain your install to have `fastparquet<0.6`?

**Comment by mdekstrand** [comment]
I'm going to go ahead and drop the `fastparquet` dep, and note the deprecation of `MultiEval`, in 0.13.
