### ISSUE TITLE
Model differences between versions

### ISSUE THREAD

**Issue by david-cortes** [lenskit/lkpy#258]
I'm fitting the following model to the MovieLens10M dataset, using the train-test split from the CSV files that come in the zipped data:
```python
model = BiasedMF(50, iterations=15, reg=0.05,
                 damping=5, bias=True, method='cd')
```

With LensKit==0.9.0, it gives a test RMSE of around 0.796, while with the latest versions it gives an RMSE of 0.907.

**Comment by mdekstrand** [comment]
Thanks for reporting this. I will need to look into what has changed in the code to see where the problem likely lies.

With "latest versions", are you testing with the last release (0.12.1), or with the current Git master?

**Comment by david-cortes** [comment]
I was testing the ones from PyPI. I think the issue might have been introduced in 0.11.

**Comment by mdekstrand** [comment]
Thanks, that helps narrow it down!

**Comment by mdekstrand** [comment]
Will look in to this before cutting the 0.13 release (currently fixing up my TODO list for finalizing that).

**Comment by mdekstrand** [comment]
@david-cortes I'm starting to dig in to this but am a little confused about the specific data. My copy of ML10M includes a `split_ratings.sh` file, but does not include any train-test CSV files. Are you using `split_ratings.sh`, or do you have another version of the files that includes train-test splits?

**Comment by david-cortes** [comment]
Sorry, just realized I was using a train-test split that I had created myself. It was basically a random 80-20 split, filtering out users and items from the test set that were not in the train set.

Here’s the script to generate it: https://github.com/david-cortes/cmfrec/blob/master/benchmark/split_ml10m_data.ipynb

And here’s the script to fit and evaluate the model:
https://github.com/david-cortes/cmfrec/blob/master/benchmark/benchmark_explicit_lenskit.ipynb

**Comment by mdekstrand** [comment]
Thanks!

I'm creating a [project](https://github.com/lenskit/lk-perf-monitor) to track model performance across LensKit versions, to get some baseline numbers here and hopefully do better detection of performance shifts over time.

**Comment by mdekstrand** [comment]
So far I can tentatively reproduce this with my data split (Global RMSE goes from 0.85 to 0.95).

**Comment by mdekstrand** [comment]
And I found it. Silly bug, change incoming.

**Comment by mdekstrand** [comment]
Turns out this affected any of our algorithms that use the `Bias` model's `transform` method. (use of `bias` itself is unaffected). Thank you very much for reporting.

In addition to adding a test for this specific bug to prevent regression, I will be using the new performance monitor project to try to prevent such regressions in the future.

**Comment by mdekstrand** [comment]
And here are the results of the test: https://nbviewer.jupyter.org/gist/mdekstrand/7b88b7059aa8b487eceb4bcc66e25164
