### ISSUE TITLE
Scaling of regularization

### ISSUE THREAD

**Issue by david-cortes** [lenskit/lkpy#259]
In the "Classic Matrix Factorization" models (`lenskit.algorithms.als.BiasedMF`, `lenskit.algorithms.funksvd.FunkSVD`), the regularization parameter is **multiplied** by the number of entries for each user and item, while in the tensorflow versions (`lenskit.algorithms.tf.BiasedMF`, `lenskit.algorithms.tf.IntegratedBiasMF`) they are **divided** by the number of users/items, yet the default values are lower for the TF versions.

Is this the intended behavior? Is there any reference paper studying the effect of having a regularization parameter that is divided instead of multiplied?

**Comment by mdekstrand** [comment]
I'm not aware of good studies on regularization scale. For Classic MF, I have tried to keep the regularization implementation as close as possible to the original paper(s). For Keras-based MF, my goal with that implementation of the regularization is to keep the regularization term's scale independent of the size of the data set. If you just multiply by the Frobenius norm of the entire matrix, then more data needs lower regularization.
