### ISSUE TITLE
lenskit-implicit install doesn't work

### ISSUE THREAD

**Issue by DataScienceUWL** [lenskit/lkpy#313]
neither pip or conda work to install the lenskit-implicit wrappers .... or at least I couldn't get them to work (wanted to compare BPR and implicit ALS)

**Comment by mdekstrand** [comment]
Yes, it hasn't hit Pip or Conda yet because it needs to be updated to Implicit 0.5.

**Comment by mdekstrand** [comment]
This has been done now — you can install with either Pip or Conda.
