### ISSUE TITLE
Allow rng specification when partitions is None  in crossfold.sample_rows

### ISSUE THREAD

**Issue by SavvinaDaniil** [lenskit/lkpy#327]
I noticed that when using sample_rows for a single train-test pair by setting partition to _None_, the rng_spec variable is not used. Code snippet from lenskit.crossfold.sample_rows follows:

```
if partitions is None:
  test = data.sample(n=size)
  tr_mask = pd.Series(True, index=data.index)
  tr_mask.loc[test.index] = False
  train = data[tr_mask]
  return TTPair(train, test)
```
I think it would be useful to be able to control the randomization even for obtaining just a single train-test pair.

**Comment by mdekstrand** [comment]
You're right - thanks for catching this.
