### ISSUE TITLE
BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

### ISSUE THREAD

**Issue by johnnyk1090** [lenskit/lkpy#370]
# Define evaluation function
def eval(aname, algo, train, test):
    fittable = util.clone(algo)
    fittable = Recommender.adapt(fittable)
    fittable.fit(train)
    users = test.user.unique()
    # now we run the recommender
    recs = batch.recommend(fittable, users, 100)
    # add the algorithm name for analyzability
    recs['Algorithm'] = aname
    return recs
    
    
    # Define algorithms
algo_ii = knn.ItemItem(20)  # Item-item collaborative filtering with k = 20
algo_als = als.BiasedMF(50)  # ALS matrix factorization with 50 factors

# Run evaluation 
all_recs = []
test_data = []

for train, test in xf.partition_users(user_ratings_df[['user', 'item', 'rating']], 5, xf.SampleFrac(0.2)):
    test_data.append(test)
        
    all_recs.append(eval('ItemItem', algo_ii, train, test))
    all_recs.append(eval('ALS', algo_als, train, test))

# Concatenate results
all_recs = pd.concat(all_recs, ignore_index=True)

BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

**Comment by mdekstrand** [comment]
This issue usually results from some kind of out-of-memory condition in the worker processes. A workaround is to reduce the number of workers, you can pass `n_jobs` to `batch.recommend`; the default caps at 4. If you pass `n_jobs=1`, then it will not use parallelism, and have reduced memory usage overall.

I would like to be able to provide better diagnostics but these issues have proven elusive to reproduce.

**Comment by johnnyk1090** [comment]
Thank you for your response. It seems to fix the issue :     recs = batch.recommend(fittable, users, 100, n_jobs=1)
However a new issue occurs : 
---> [12](vscode-notebook-cell:?execution_count=20&line=12)     all_recs.append(eval('ItemItem', algo_ii, train, test))
---> [10](vscode-notebook-cell:?execution_count=19&line=10) recs = batch.recommend(fittable, users, 100, n_jobs=1)
--> [477](file:///C:/Users/anaconda3/envs/virtual/lib/site-packages/lenskit/algorithms/item_knn.py:477) assert np.sum(np.logical_not(np.isnan(rate_v))) == len(ri_pos)

AssertionError: 

Possibly indicates a mismatch between the number of ratings and the number of recommendations being generated...

any sugesstions ?

**Comment by mdekstrand** [comment]
Could you paste the complete backtrace? The line numbers alone are not enough context.
