### ISSUE TITLE
duplicate ratings give error in item_knn

### ISSUE THREAD

**Issue by tdpessem** [lenskit/lkpy#46]
I used a dataset that contains duplicate ratings (re-ratings). item_knn gave an error on line 329:
assert np.sum(np.logical_not(np.isnan(rate_v))) == len(ri_pos)

removing the duplicate ratings from the dataset solved the issue.

**Comment by mdekstrand** [comment]
Yes, item-knn won't work with duplicate ratings. Most of the algorithms currently present won't.

Would a diagnostic warning or error that re-rates are unsupported be a good way to handle this?

**Comment by tdpessem** [comment]
I think a diagnostic warning or error would be a good idea. This indicates the reason that the algorithm stops working.
