### ISSUE TITLE
Getting started code still not executable from conda install

### ISSUE THREAD

**Issue by rburke2233** [lenskit/lkpy#66]
Issue #56 is closed, but the problem still exists. The supplied Getting Started code fails at `utils.clone()`

See attached.

<img width="1015" alt="screen shot 2019-01-28 at 8 39 06 pm" src="https://user-images.githubusercontent.com/2395210/51882639-d7f9e800-233c-11e9-97b3-f53bcff56ff7.png">

Conda thinks I have 0.5.0 installed. 

<img width="687" alt="screen shot 2019-01-28 at 8 38 43 pm" src="https://user-images.githubusercontent.com/2395210/51882648-e6480400-233c-11e9-80ff-ed551e0a6c71.png">

When use `pip` and the gihub repository, I do not get the error.

**Comment by mdekstrand** [comment]
We're about ready for 0.6 and this is fixed there.

I am also integrating [nbval](https://github.com/computationalmodelling/nbval) to include notebook validation in our test processes.
