### ISSUE TITLE
Rewrite docs for recommend=None and n=None for topn

### ISSUE THREAD

**Issue by keener101** [lenskit/lkpy#83]
Docs imply that `n=None` (`batch.recommend`) and `recommend=None` (`multieval`) will result in complete recommendation lists. This is not the case. Will try with `n=0` / `n=-1` and see if that works.

**Comment by keener101** [comment]
n = -1 results in the correct functionality.

**Comment by mdekstrand** [comment]
So, I like `recommend=None` for that. What if we used `recommend=False` to turn off recommendation? Is it too confusing to have a false-y value (e.g. `None`) enable recommendation with unlimited lists?

**Comment by keener101** [comment]
I think so. The idea from the meeting (I think) was..

All false-y values (None, False, 0) = turn off recommendation
Number values (1, 2, 100) = that size of recommendation list
True = full recommendation list

**Comment by mdekstrand** [comment]
@keener101 Yes, that is correct!
