### ISSUE TITLE
fastparquet does not like compression='snappy'.

### ISSUE THREAD

**Issue by keener101** [lenskit/lkpy#90]
I had to uninstall `fastparquet` because it said `compression='snappy'` wasn't supported. Is this just on my end for some reason?

**Comment by mdekstrand** [comment]
If you have `fastparquet`, it also requires `python-snappy`. I recommend installing both - it will make multi-eval more efficient.

**Comment by mdekstrand** [comment]
The Conda packages depend on both `fastparquet` and `python-snappy`, so this only comes up when installing LensKit from Pip or git. I will close the issue.

**Comment by mdekstrand** [comment]
For documentation purposes: we cannot make the LensKit PyPI package depend on `fastparquet`, because it does not publish binary wheels and thus the installation is prone to failure. Conda is the recommended way to install published releases of LensKit.
