### ISSUE TITLE
nprocs seems to cause issues.

### ISSUE THREAD

**Issue by keener101** [lenskit/lkpy#92]
`nprocs = 12` and `nprocs=24` both caused fatal crashes, very quickly into the `MultiEval` process. We should investigate closer. 

![image](https://user-images.githubusercontent.com/29421368/55093738-9b1b4a80-507a-11e9-9d9d-042d4664f0e4.png)

**Comment by mdekstrand** [comment]
Try with latest `master` :)

**Comment by mdekstrand** [comment]
@keener101 what's the status on this?

**Comment by mdekstrand** [comment]
Going to call this closed now.
